/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "spliiit.h"

ListeCompte liste;

Compte MES_COMPTES[10];

Abonnement MES_ABONNEMENTS[10];

static int cpt = 0;
int nb_max_compte = 20;
	

Service services[] = {
	    {1, "Spotify", "Service de streaming musical", 9.99, 1000},
	    {2, "YouTube", "Plateforme de partage de vidéos", 0, 10000},
	    {3, "Netflix", "Service de streaming vidéo", 12.99, 5000},
	    {4, "Amazon Prime Video", "Service de streaming vidéo et livraison", 8.99, 8000},
	    {5, "Apple Music", "Service de streaming musical d'Apple", 9.99, 1500},
	    {6, "Disney+", "Plateforme de streaming pour contenus Disney", 7.99, 3000},
	    {7, "Hulu", "Service de streaming vidéo et TV en direct", 5.99, 2000},
	    {8, "Twitch", "Plateforme de streaming pour les jeux vidéo", 4.99, 5000},
	    {9, "HBO Max", "Service de streaming pour les contenus HBO", 14.99, 2500},
	    {10, "SoundCloud", "Plateforme de streaming musical indépendant", 7.99, 3000}
	};


void copyCompte(Compte * dest, Compte * src){
	dest->id =  src->id;
	strcpy(dest->pseudo, src->pseudo);
	strcpy(dest->pays, src->pays);
	strcpy(dest->passwd, src->passwd);
	strcpy(dest->nom, src->nom);
	strcpy(dest->prenom, src->prenom);
	dest->age = src->age;
	dest->role = src->role;
}


bool_t *
init_1_svc(void *argp, struct svc_req *rqstp)
{
	static bool_t  result;
	liste.nb_instance = 0;
	/*
	 * insert server code here
	 */

	//liste.comptes = NULL;
	//MES_COMPTES = (Compte *) malloc(sizeof(Compte) * nb_max_compte);
	//if (MES_COMPTES == NULL)
	//{
	//	printf("Erreur malloc\n");
	//result = false;
	//	exit(-1);
	//}

	//Creation d'un compte admin
	Compte admin = {1, "123456@", "Bacar", "Houssam", 22, 'A', "e22010141", "Mayotte", 1};
	copyCompte(&MES_COMPTES[cpt], &(admin));
	cpt++;

	Compte admin2 = {2, "azerty", "Mohamed", "Yassine", 34, 'A', "moh_yass", "Australie", 1};
	copyCompte(&MES_COMPTES[cpt], &(admin2));
	cpt++;

	printf("[{1, '123456@', 'Bacar', 'Houssam', 22, 'A', 'e22010141', 'Mayotte', 1}]\n");
	printf("[{2, 'azerty', 'Mohamed', 'Yassine', 34, 'A', 'moh_yass', 'Australie', 1}]\n");

	for(int i = 0; i < 5; i++){
		MES_ABONNEMENTS[i].abn_id = i;
		char buffer[256] = {0};
		sprintf(buffer, "ABN-%d", i);
		strcpy(MES_ABONNEMENTS[i].abn_intitule, buffer);
		sprintf(buffer, "ABN-%d--Serv--%d", i, i*2);
		strcpy(MES_ABONNEMENTS[i].intituleService, buffer);
		sprintf(buffer, "1%d032024", i);
		strcpy(MES_ABONNEMENTS[i].date_prelevement, buffer);
		MES_ABONNEMENTS[i].tarif = i * 0.9;
		MES_ABONNEMENTS[i].nombrePlace = i+3;
		MES_ABONNEMENTS[i].idCompte = 1;
		MES_ABONNEMENTS[i].idService = 1;
		MES_ABONNEMENTS[i].partage = 0;
		MES_ABONNEMENTS[i].partage_custom = 1;
	}

	return &result;
}

Compte *
inscription_1_svc(Information *infos, struct svc_req *rqstp)
{
	static Compte  result;
	infos->compte.id = cpt+1;
	copyCompte(&MES_COMPTES[cpt], &(infos->compte));

	copyCompte(&result, &(infos->compte));

	cpt++;
	printf("Compte n_%d inscrit !\n", cpt);
	
	for(int i = 0; i < cpt; i++){
		printf("Checking: %s ", MES_COMPTES[i].nom);
		printf("-> %s ...\n", MES_COMPTES[i].passwd);
	}	

	return &result;
}

int *
connexion_1_svc(Information *info, struct svc_req *rqstp)
{
	static int  result;
	result = -1;
	printf("Requete de connexion : Verification...\n%s : %s\n",info->compte.pseudo, info->compte.passwd );
	for(int i = 0; i < cpt; i++){
		if ((strcmp(MES_COMPTES[i].pseudo, info->compte.pseudo) == 0) 
			&& 
			(strcmp(MES_COMPTES[i].passwd, info->compte.passwd) == 0))
		{
			printf("Compte trouvé !\n");
			result = 1;
			return &result;
		}
	}
	return &result;
}


ListeService *
lister_services_1_svc(void *argp, struct svc_req *rqstp)
{
	static ListeService  result;

	result.taille = 0;
	result.capamax = 10;

	for (int i = 0; i < result.capamax; i++)
	{
		result.services[i].id = services[i].id;
		strcpy(result.services[i].intitule, services[i].intitule);
		strcpy(result.services[i].description, services[i].description);
		result.services[i].prix = services[i].prix;
		result.services[i].nbPlaceInitial = services[i].nbPlaceInitial;
		result.taille++;
	}

	return &result;
}

int *
desinscription_1_svc(Information *info, struct svc_req *rqstp)
{
	static int  result;

	printf("Requete de connexion : Suppression de ...\n%s : %s\n",info->compte.pseudo, info->compte.passwd );
	for(int i = 0; i < cpt; i++){
		if ((strcmp(MES_COMPTES[i].pseudo, info->compte.pseudo) == 0) 
			&& 
			(strcmp(MES_COMPTES[i].passwd, info->compte.passwd) == 0))
		{
			printf("Compte trouvé !\n");
			result = 1;
			strcmp(MES_COMPTES[i].pseudo, "-1");
			strcmp(MES_COMPTES[i].passwd, "-1");
			MES_COMPTES[i].id = -1;
			strcpy(MES_COMPTES[i].pays, "-1");
			strcpy(MES_COMPTES[i].nom, "-1");
			strcpy(MES_COMPTES[i].prenom, "-1");
			MES_COMPTES[i].age = -1;
			MES_COMPTES[i].role = 0;
			return &result;
		}
	}

	return &result;
}

ListeAbonnement *
lister_abonnement_1_svc(void *argp, struct svc_req *rqstp)
{
	static ListeAbonnement  result;

	result.nb_abonnement = 5;

	for (int i = 0; i < result.nb_abonnement; i++)
	{	
		result.abonnements[i].abn_id = MES_ABONNEMENTS[i].abn_id;
		strcpy(result.abonnements[i].abn_intitule, MES_ABONNEMENTS[i].abn_intitule);
		strcpy(result.abonnements[i].intituleService, MES_ABONNEMENTS[i].intituleService);
		strcpy(result.abonnements[i].date_prelevement, MES_ABONNEMENTS[i].date_prelevement);
		result.abonnements[i].tarif = MES_ABONNEMENTS[i].tarif;
		result.abonnements[i].nombrePlace = MES_ABONNEMENTS[i].nombrePlace;
		result.abonnements[i].idCompte = MES_ABONNEMENTS[i].idCompte;
		result.abonnements[i].idCompte = MES_ABONNEMENTS[i].idService;
		result.abonnements[i].partage = MES_ABONNEMENTS[i].partage;
		result.abonnements[i].partage_custom = MES_ABONNEMENTS[i].partage_custom;
	}

	
	return &result;
}



Abonnement *
creer_abonnement_1_svc(Information *info, struct svc_req *rqstp){
    static Abonnement result;
    printf("Creation d'un abonnement !..\n");
    // Copier les informations de l'abonnement à partir de la structure d'information
    result.abn_id = info->abonnement.abn_id;
    strcpy(result.abn_intitule, info->abonnement.abn_intitule);
    strcpy(result.intituleService, info->abonnement.intituleService);
    strcpy(result.date_prelevement, info->abonnement.date_prelevement);
    result.tarif = info->abonnement.tarif;
    result.nombrePlace = info->abonnement.nombrePlace;
    result.idCompte = info->abonnement.idCompte;
    result.idService = info->abonnement.idService;
    result.partage = info->abonnement.partage;
    result.partage_custom = info->abonnement.partage_custom;
    
    // Ajouter le nouvel abonnement à MES_ABONNEMENTS (s'il y a de la place)
    // Par exemple, si vous voulez ajouter l'abonnement au premier emplacement disponible :
    int i;
    for (i = 0; i < 10; i++) {
        if (MES_ABONNEMENTS[i].abn_id == 0) { // Vérifie si l'emplacement est vide
            // Copier en profondeur chaque membre de la structure Abonnement
            MES_ABONNEMENTS[i].abn_id = result.abn_id;
            strcpy(MES_ABONNEMENTS[i].abn_intitule, result.abn_intitule);
            strcpy(MES_ABONNEMENTS[i].intituleService, result.intituleService);
            strcpy(MES_ABONNEMENTS[i].date_prelevement, result.date_prelevement);
            MES_ABONNEMENTS[i].tarif = result.tarif;
            MES_ABONNEMENTS[i].nombrePlace = result.nombrePlace;
            MES_ABONNEMENTS[i].idCompte = result.idCompte;
            MES_ABONNEMENTS[i].idService = result.idService;
            MES_ABONNEMENTS[i].partage = result.partage;
            MES_ABONNEMENTS[i].partage_custom = result.partage_custom;
            break;
        }
    }
    
    return &result;
}



int *
payer_abonnement_1_svc(Abonnement *argp, struct svc_req *rqstp)
{
	static int  result;

	printf("Payement d'un abonnement...\n");

	return &result;
}
