/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "spliiit.h"


enum MENU{
	INSCRIPTION=1,
	VOIR_SERVICES=2,
	LISTER_CO_ABONNEMENT,
	AJOUTER_ABONNEMENT, 
	PAYER_ABONNEMENT,
	CONNEXION=20,
	DECONNECTER,
	DESINSCRIRE,
	QUITTER=30,
};

typedef enum MENU MENU;



void copyCompte(Compte * dest, Compte * src){
	dest->id =  src->id;
	strcpy(dest->pseudo, src->pseudo);
	strcpy(dest->pays, src->pays);
	strcpy(dest->passwd, src->passwd);
	strcpy(dest->nom, src->nom);
	strcpy(dest->prenom, src->prenom);
	dest->age = src->age;
	dest->role = src->role;
}


void
partageur_1(char *host,  Compte * nouveauCompte, MENU menu, int * mode_session)
{
	CLIENT *clnt;
	bool_t  *result_1;
	char *init_1_arg;
	Compte  *result_2;
	Information  inscription_1_arg;
	int  *result_3;
	Information  connexion_1_arg;
	ListeService  *result_4;
	char *lister_services_1_arg;
	int  *result_5;
	Information  desinscription_1_arg;
	ListeAbonnement  *result_6;
	char *lister_abonnement_1_arg;
	Abonnement  *result_7;
	Information  creer_abn;


	int  *result_8;
	Abonnement  payer_abonnement_1_arg;

	Compte  *compte = (Compte *) malloc(sizeof(Compte));
	if(compte == NULL) 
		exit (1);
	Information  info;
	
	if (nouveauCompte != NULL)
		copyCompte(&(info.compte), nouveauCompte);

	
	info.listeCompte.nb_instance = 0;

#ifndef	DEBUG
	clnt = clnt_create (host, PARTAGEUR, SPLIIIT_V1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = init_1((void*)&init_1_arg, clnt);
	if (result_1 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	switch(menu){
		case INSCRIPTION:
			//
			compte = inscription_1(&info, clnt);
			if (compte == (Compte *) NULL) {
				clnt_perror (clnt, "call failed");
			}
			
			printf("Information de compte : \nid : %d\n Pseudo: %s\n Nom : %s\nPrenom : %s\n Age : %d \n Role : %d\n \n",
				compte->id, compte->pseudo, compte->nom, compte->prenom, compte->age, compte->role);
			//
			break;
		case CONNEXION:
			
			result_3 = connexion_1(&info, clnt);
			if (result_3 == (int *) NULL) {
				clnt_perror (clnt, "call failed");
			}
			if((*result_3) == -1 ){
				printf("\033[31m Compte inconnue ! Veuillez re-essayer\033[00m\n");
				
			}else{
				*mode_session = 1;
				printf("@@========Connecté==========@@\n");
			}

			break;
		case VOIR_SERVICES:
			printf("Liste des services : \n");
				result_4 = lister_services_1((void*)&lister_services_1_arg, clnt);
				if (result_4 == (ListeService *) NULL) {
					clnt_perror (clnt, "call failed");
				}

				for (int i = 0; i < 3; i++)
				{
					printf("#########\n\033[31mid:%d\033[00m\n"
						    "\t\033[33m|titre:\033[30m%s\033[00m\n"
						    "SERVICE \033[33m|desc:\033[30m%s\033[00m\n"
						    "\t\033[33m|prix:\033[30m%lf\033[00m\n"
						    "________\033[33m|place:\033[30m%d\033[00m\n", 
						result_4->services[i].id, result_4->services[i].intitule, result_4->services[i].description, 
						result_4->services[i].prix, result_4->services[i].nbPlaceInitial);
				}
			break;
		case LISTER_CO_ABONNEMENT:
			printf("Liste des co-abonnements : \n");
				result_6 = lister_abonnement_1((void*)&lister_abonnement_1_arg, clnt);
			if (result_6 == (ListeAbonnement *) NULL) {
				clnt_perror (clnt, "call failed");
			}

			
			printf("______________________________________\n");
			printf("|            Abonnements              |\n");
			printf("|____________________________________|\n");
			for(int i = 0; i < 3; i++){
			    printf("|Abonnement ID: %d\n", result_6->abonnements[i].abn_id);
			    printf("|Intitulé du service: %s\n", result_6->abonnements[i].abn_intitule);
			    printf("|Date de prélèvement: %s\n", result_6->abonnements[i].date_prelevement);
			    printf("|Tarif: %.2f\n", result_6->abonnements[i].tarif);
			    printf("|Nombre de places: %d\n", result_6->abonnements[i].nombrePlace);
			    printf("|ID du compte: %d\n", result_6->abonnements[i].idCompte);
			    printf("|ID du service: %d\n", result_6->abonnements[i].idService);
			    printf("|Partage: %d\n", result_6->abonnements[i].partage);
			    printf("|Partage personnalisé: %d\n", result_6->abonnements[i].partage_custom);
			    printf("________________________\n");
			}

			break;
		case DESINSCRIRE:
			printf("DESINSCRIRE\n");
			result_5 = desinscription_1(&desinscription_1_arg, clnt);
			if (result_5 == (int *) NULL) {
				clnt_perror (clnt, "call failed");
			}
			break;
		case AJOUTER_ABONNEMENT:
			printf("Ajouter co-abonnements : \n");
			// Instanciation d'un abonnement pour le service Avast
			//Abonnement abonnement;

			creer_abn.abonnement.abn_id = 1001; // ID de l'abonnement
			strcpy(creer_abn.abonnement.abn_intitule, "Avast"); // Intitulé du service
			strcpy(creer_abn.abonnement.date_prelevement, "2024-03-22"); // Date de prélèvement
			creer_abn.abonnement.tarif = 29.99; // Tarif de l'abonnement
			creer_abn.abonnement.nombrePlace = 1; // Nombre de places
			creer_abn.abonnement.idCompte = 12345; // ID du compte associé
			creer_abn.abonnement.idService = 9876; // ID du service
			creer_abn.abonnement.partage = 0; // Paramètre de partage (0 si non partagé, 1 si partagé)
			creer_abn.abonnement.partage_custom = 0; // Paramètre de partage personnalisé (0 si non personnalisé, 1 si personnalisé)


			printf("______________________________________\n");
			printf("|          Ajout d'un abonnement      |\n");
			printf("|____________________________________|\n");

			printf("Veuillez entrer les détails de l'abonnement :\n");

			printf("Abonnement ID: %d\n", creer_abn.abonnement.abn_id);
			printf("Intitulé du service: %s\n", creer_abn.abonnement.abn_intitule);
			printf("Date de prélèvement: %s\n", creer_abn.abonnement.date_prelevement);
			printf("Tarif: %.2f\n", creer_abn.abonnement.tarif);
			printf("Nombre de places: %d\n", creer_abn.abonnement.nombrePlace);
			printf("ID du compte: %d\n", creer_abn.abonnement.idCompte);
			printf("ID du service: %d\n", creer_abn.abonnement.idService);
			printf("Partage: %d\n", creer_abn.abonnement.partage);
			printf("Partage personnalisé: %d\n", creer_abn.abonnement.partage_custom);

			result_7 = creer_abonnement_1(&creer_abn, clnt);
			if (result_7 == (Abonnement *) NULL) {
				clnt_perror (clnt, "call failed");
			}

			printf("______________________________________\n");
			printf("|          Ajout d'un abonnement      |\n");
			printf("|_______________EFFECTUÉ______________|\n\n");

			break;
		case PAYER_ABONNEMENT:
			printf("Payer mon co-abonnements : \n");
			payer_abonnement_1_arg.abn_id = 1; // ID de l'abonnement
			strcpy(payer_abonnement_1_arg.abn_intitule, "Avast"); // Intitulé du service
			strcpy(payer_abonnement_1_arg.date_prelevement, "22032024"); // Date de prélèvement
			payer_abonnement_1_arg.tarif = 29.99; // Tarif de l'abonnement
			printf("Augmentation des tarif de : %lf\n", payer_abonnement_1_arg.tarif);
			payer_abonnement_1_arg.nombrePlace = 1; // Nombre de places
			payer_abonnement_1_arg.idCompte = 1; // ID du compte associé
			payer_abonnement_1_arg.idService = 4; // ID du service
			payer_abonnement_1_arg.partage = 0; // Paramètre de partage (0 si non partagé, 1 si partagé)
			payer_abonnement_1_arg.partage_custom = 0; // Paramètre de partage personnalisé (0 si non personnalisé, 1 si personnalisé)


			// Simulation du paiement
			// (Ajoutez ici le code pour le traitement du paiement)
			printf("Paiement effectué pour l'abonnement Avast.\n\n");

			result_8 = payer_abonnement_1(&payer_abonnement_1_arg, clnt);
			if (result_8 == (int *) NULL) {
				clnt_perror (clnt, "call failed");
			}
			break;
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void etape_inscription(Compte * nouveauCompte){
	nouveauCompte->id=0;
	char prenom[10];
	char nom[10];
	char pays[20];
	char pseudo[50];
	char passwd[12];
	char c_passwd[12];
	memset(passwd, 0, 12);
	memset(c_passwd, 0, 12);
	printf("=================================\nInscription : \n");

	printf("Pseudo : e22010142\n");
	strcpy(pseudo, "e22010142");

	printf("Entrer le nom : BACAR\n");
	strcpy(nom, "BACAR");
	
	printf("Entrer le prenom : Houssam\n");
	strcpy(prenom, "Houssam");
	printf("Votre Pays : FRANCE\n");
	strcpy(pays, "FRANCE");

	strcpy(nouveauCompte->pseudo, pseudo);
	strcpy(nouveauCompte->pays, pays);
	strcpy(nouveauCompte->nom, nom);
	strcpy(nouveauCompte->prenom, prenom);
	
	//do{
		printf("Entrer votre age  (please: >16 ): 25\n");
		//scanf("%d", &(nouveauCompte->age));
		nouveauCompte->age = 25;
	//}while(nouveauCompte->age < 17	);
	printf("\n=================================\n");
	//do {
		printf("Mot de passe: Mot2Pas5e\n");
		strcpy(passwd, "Mot2Pas5e");
		printf("Confirmation de mot de passe: Mot2Pas5e\n");
		strcpy(c_passwd, "Mot2Pas5e");
		printf("____________________________\n");
	//}while(strcmp(passwd, c_passwd) != 0);

	strcpy(nouveauCompte->passwd, passwd);
}

void etape_connex(Compte * connex){
	memset(connex->pseudo, 0, 50);
	memset(connex->passwd, 0, 12);
	printf("===========\nConnexion:\n");
	printf("Pseudo : e22010142\n");
	strcpy(connex->pseudo, "e22010142");
	printf("Mot de passe: Mot2Pas5e\n");
	strcpy(connex->passwd, "Mot2Pas5e");
	printf("... en cours....\n");

}

void quitter_application(){
	exit(0);
}



int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	partageur_1 (host, NULL, -1, NULL);
	int active = 0;
	int mode_session = 0;
	printf("Bienvenue sur spliiit ! \n");

	Compte nouveauCompte;
	Compte nouveauConnexion;
	etape_inscription(&nouveauCompte);
	printf("-> @==Inscription==@\n");
	partageur_1(host, &nouveauCompte, INSCRIPTION, &mode_session);

	printf("\n-> @==Étape de connexion==@\n");
	etape_connex(&nouveauConnexion);

	printf("\n-> @==Connexion==@\n");
	partageur_1(host, &nouveauConnexion, CONNEXION, &mode_session);

	printf("\n-> @==Voir services==@\n");
	partageur_1(host, NULL, VOIR_SERVICES, NULL);

	printf("\n-> @==Lister les comptes abonnés==@\n");
	partageur_1(host, NULL, LISTER_CO_ABONNEMENT, NULL);

	printf("\n-> @==Payer l'abonnement==@\n");
	partageur_1(host, NULL, PAYER_ABONNEMENT, NULL);

	printf("\n-> @==Lister les comptes abonnés après paiement==@\n");
	partageur_1(host, NULL, LISTER_CO_ABONNEMENT, NULL);

	printf("\n@==Deconnexion==@\n");
	partageur_1(host, &nouveauConnexion, CONNEXION, &mode_session);

	printf("\n-> @==Désinscription==@\n");
	partageur_1(host, NULL, DESINSCRIRE, NULL);



	/*
	do{
		printf("=================================\\n");
		printf("Menu : \n [%d] Inscriptions | [%d] Connexion | [%d] Services | [%d] Trouver co-abonnement \n",
				INSCRIPTION, CONNEXION, VOIR_SERVICES, LISTER_CO_ABONNEMENT);
		printf(" [%d] Quitter !\n\n", QUITTER);
		scanf("%d", &active);
		Compte nouveauCompte;
		Compte nouveauConnexion;
		switch(active){
			
			case CONNEXION:
				etape_connex(&nouveauConnexion);
				partageur_1 (host, &nouveauConnexion, CONNEXION, &mode_session);
				break;
			case VOIR_SERVICES:
				//etape_connex(&nouveauConnexion);
				partageur_1 (host, NULL, VOIR_SERVICES, NULL);
				break;
			case LISTER_CO_ABONNEMENT:
				partageur_1(host, NULL, LISTER_CO_ABONNEMENT, NULL);
				break;
			case QUITTER:
				printf("Au revoir !\n");
				quitter_application();
				break;
			default:
				printf("Saisie incorrect !\n");
				break;
		}

		if (mode_session == 1)
		{
			int choix = -1;
			do{
				
				do{
					printf("@@========Connecté==========@@\n");
					printf("Menu : \n [%d] Deconnexion | [%d] Services | [%d] Trouver co-abonnement  \n",
						DECONNECTER, VOIR_SERVICES, LISTER_CO_ABONNEMENT);
					printf("   [%d] Ajouter un Abonnement | [%d] Payer un abonnement | [%d] Desinscrire  \n", 
						AJOUTER_ABONNEMENT, PAYER_ABONNEMENT, DESINSCRIRE );
				}while(scanf("%d", &choix) < 0);

				switch(choix){
					case DECONNECTER:
						mode_session = -1;
						printf("@==Deconnexion==@\n");
						break;
					case PAYER_ABONNEMENT:
						partageur_1(host, NULL, PAYER_ABONNEMENT, NULL);
						break;
					case LISTER_CO_ABONNEMENT:
						partageur_1(host, NULL, LISTER_CO_ABONNEMENT, NULL);
						break;
					case AJOUTER_ABONNEMENT:
						partageur_1(host, NULL, LISTER_CO_ABONNEMENT, NULL);
						break;
					case DESINSCRIRE:
						partageur_1(host, NULL, DESINSCRIRE, NULL);
						break;
				}

			}while(mode_session == 1);
		}

	}while(active != 4);
	
	*/
	
exit (0);
}